services:

  # Base containers
  linuxbase:
    build: ./linuxbase
    container_name: linuxbase
    image: linuxbase

  # Application containers (extending base containers)
  pythonbase:
    build: ./pythonbase
    container_name: pythonbase
    image: pythonbase
    depends_on:
      - linuxbase
    ports:
      - "4213:4213"

  # Database containers
  pgduckdb:
    image: pgduckdb/pgduckdb:17-v0.1.0
    container_name: pgduckdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: pgduckdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgduckdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      retries: 5
    networks:
      - sonnet_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sonnet.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pgduckdb
    networks:
      - sonnet_network

  # Storage containers
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    networks:
      - sonnet_network

volumes:
  pgduckdb_data:
   driver: local
  pgadmin_data:
   driver: local
  minio_data:
   driver: local
  data:
   driver: local

networks:
  sonnet_network:
    driver: bridge
