version: '3.8'

services:

  pythonbase:
    build: ./pythonbase
    container_name: pythonbase
    image: pythonbase
    depends_on:
      - linuxbase

  linuxbase:
    build: ./linuxbase
    container_name: linuxbase
    image: linuxbase


  pgduckdb:
    image: pgduckdb/pgduckdb:17-v0.1.0
    container_name: pgduckdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgduckdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

volumes:
  pgduckdb_data:
   driver: local
  data:
   driver: local