services:

  pythonbase:
    build:
      context: ./pythonbase
    container_name: pythonbase
    image: pythonbase
    depends_on:
      linuxbase:
        condition: service_completed_successfully
    ports:
      - "4213:4213"

  linuxbase:
    build:
      context: ./linuxbase
    container_name: linuxbase
    image: linuxbase

  pgduckdb:
    image: pgduckdb/pgduckdb:17-v0.1.0
    container_name: pgduckdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgduckdb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]


  duckdb:
    build:
      context: ./duckdb
    container_name: duckdb
    ports:
      - "4321:4321"
    volumes:
      - duckdb_data:/root/duckdb

  dbgate:
      image: dbgate/dbgate
      container_name: dbgate
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - dbgate_data:/root/.dbgate
      environment:
        CONNECTIONS: "pgduckdb,duckdb"

        LABEL_pgduckdb: "Postgres (pgduckdb)"
        SERVER_pgduckdb: "pgduckdb"
        PORT_pgduckdb: "5432"
        USER_pgduckdb: "postgres"
        PASSWORD_pgduckdb: "postgres"
        ENGINE_pgduckdb: "postgres@dbgate-plugin-postgres"

        # LABEL_duckdb_file: "DuckDB"
        # FILE_duckdb_file: "/var/lib/duckdb/data/my_database.duckdb"
        # ENGINE_duckdb_file: "duckdb@dbgate-plugin-duckdb"

volumes:
  pgduckdb_data:
    driver: local
  minio_data:
    driver: local
  dbgate_data:
    driver: local
  duckdb_data:
    driver: local