from io import StringIO
import os

import psycopg2


def connect_to_db():
    try:
        # Use environment variables for configuration
        connection = psycopg2.connect(
            dbname=os.getenv("DB_NAME", "postgres"),
            user=os.getenv("DB_USER", "postgres"),
            password=os.getenv("DB_PASSWORD", "postgres"),
            host=os.getenv("DB_HOST", "pgduckdb"),
            port=os.getenv("DB_PORT", 5432),
        )
        return connection
    except Exception as e:
        print(f"The error '{e}' occurred.")
        return None


def copy_csv_to_db(conn, csv_file, table_name):
    with conn.cursor() as cur:
        with open(csv_file, "r") as file:
            cur.copy_expert(f"COPY {table_name} FROM STDIN WITH CSV HEADER", file)
        conn.commit()
        print(f"Copied data from {csv_file} into the {table_name} table.")


def create_claims_table(cur):
    ddl_statement = """
        CREATE TABLE IF NOT EXISTS raw_claims (
            DESYNPUF_ID TEXT,
            CLM_ID TEXT,
            CLM_FROM_DT TEXT,
            CLM_THRU_DT TEXT,
            ICD9_DGNS_CD_1 TEXT,
            ICD9_DGNS_CD_2 TEXT,
            ICD9_DGNS_CD_3 TEXT,
            ICD9_DGNS_CD_4 TEXT,
            ICD9_DGNS_CD_5 TEXT,
            ICD9_DGNS_CD_6 TEXT,
            ICD9_DGNS_CD_7 TEXT,
            ICD9_DGNS_CD_8 TEXT,
            PRF_PHYSN_NPI_1 TEXT,
            PRF_PHYSN_NPI_2 TEXT,
            PRF_PHYSN_NPI_3 TEXT,
            PRF_PHYSN_NPI_4 TEXT,
            PRF_PHYSN_NPI_5 TEXT,
            PRF_PHYSN_NPI_6 TEXT,
            PRF_PHYSN_NPI_7 TEXT,
            PRF_PHYSN_NPI_8 TEXT,
            PRF_PHYSN_NPI_9 TEXT,
            PRF_PHYSN_NPI_10 TEXT,
            PRF_PHYSN_NPI_11 TEXT,
            PRF_PHYSN_NPI_12 TEXT,
            PRF_PHYSN_NPI_13 TEXT,
            TAX_NUM_1 TEXT,
            TAX_NUM_2 TEXT,
            TAX_NUM_3 TEXT,
            TAX_NUM_4 TEXT,
            TAX_NUM_5 TEXT,
            TAX_NUM_6 TEXT,
            TAX_NUM_7 TEXT,
            TAX_NUM_8 TEXT,
            TAX_NUM_9 TEXT,
            TAX_NUM_10 TEXT,
            TAX_NUM_11 TEXT,
            TAX_NUM_12 TEXT,
            TAX_NUM_13 TEXT,
            HCPCS_CD_1 TEXT,
            HCPCS_CD_2 TEXT,
            HCPCS_CD_3 TEXT,
            HCPCS_CD_4 TEXT,
            HCPCS_CD_5 TEXT,
            HCPCS_CD_6 TEXT,
            HCPCS_CD_7 TEXT,
            HCPCS_CD_8 TEXT,
            HCPCS_CD_9 TEXT,
            HCPCS_CD_10 TEXT,
            HCPCS_CD_11 TEXT,
            HCPCS_CD_12 TEXT,
            HCPCS_CD_13 TEXT,
            LINE_NCH_PMT_AMT_1 TEXT,
            LINE_NCH_PMT_AMT_2 TEXT,
            LINE_NCH_PMT_AMT_3 TEXT,
            LINE_NCH_PMT_AMT_4 TEXT,
            LINE_NCH_PMT_AMT_5 TEXT,
            LINE_NCH_PMT_AMT_6 TEXT,
            LINE_NCH_PMT_AMT_7 TEXT,
            LINE_NCH_PMT_AMT_8 TEXT,
            LINE_NCH_PMT_AMT_9 TEXT,
            LINE_NCH_PMT_AMT_10 TEXT,
            LINE_NCH_PMT_AMT_11 TEXT,
            LINE_NCH_PMT_AMT_12 TEXT,
            LINE_NCH_PMT_AMT_13 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_1 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_2 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_3 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_4 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_5 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_6 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_7 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_8 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_9 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_10 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_11 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_12 TEXT,
            LINE_BENE_PTB_DDCTBL_AMT_13 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_1 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_2 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_3 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_4 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_5 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_6 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_7 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_8 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_9 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_10 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_11 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_12 TEXT,
            LINE_BENE_PRMRY_PYR_PD_AMT_13 TEXT,
            LINE_COINSRNC_AMT_1 TEXT,
            LINE_COINSRNC_AMT_2 TEXT,
            LINE_COINSRNC_AMT_3 TEXT,
            LINE_COINSRNC_AMT_4 TEXT,
            LINE_COINSRNC_AMT_5 TEXT,
            LINE_COINSRNC_AMT_6 TEXT,
            LINE_COINSRNC_AMT_7 TEXT,
            LINE_COINSRNC_AMT_8 TEXT,
            LINE_COINSRNC_AMT_9 TEXT,
            LINE_COINSRNC_AMT_10 TEXT,
            LINE_COINSRNC_AMT_11 TEXT,
            LINE_COINSRNC_AMT_12 TEXT,
            LINE_COINSRNC_AMT_13 TEXT,
            LINE_ALOWD_CHRG_AMT_1 TEXT,
            LINE_ALOWD_CHRG_AMT_2 TEXT,
            LINE_ALOWD_CHRG_AMT_3 TEXT,
            LINE_ALOWD_CHRG_AMT_4 TEXT,
            LINE_ALOWD_CHRG_AMT_5 TEXT,
            LINE_ALOWD_CHRG_AMT_6 TEXT,
            LINE_ALOWD_CHRG_AMT_7 TEXT,
            LINE_ALOWD_CHRG_AMT_8 TEXT,
            LINE_ALOWD_CHRG_AMT_9 TEXT,
            LINE_ALOWD_CHRG_AMT_10 TEXT,
            LINE_ALOWD_CHRG_AMT_11 TEXT,
            LINE_ALOWD_CHRG_AMT_12 TEXT,
            LINE_ALOWD_CHRG_AMT_13 TEXT,
            LINE_PRCSG_IND_CD_1 TEXT,
            LINE_PRCSG_IND_CD_2 TEXT,
            LINE_PRCSG_IND_CD_3 TEXT,
            LINE_PRCSG_IND_CD_4 TEXT,
            LINE_PRCSG_IND_CD_5 TEXT,
            LINE_PRCSG_IND_CD_6 TEXT,
            LINE_PRCSG_IND_CD_7 TEXT,
            LINE_PRCSG_IND_CD_8 TEXT,
            LINE_PRCSG_IND_CD_9 TEXT,
            LINE_PRCSG_IND_CD_10 TEXT,
            LINE_PRCSG_IND_CD_11 TEXT,
            LINE_PRCSG_IND_CD_12 TEXT,
            LINE_PRCSG_IND_CD_13 TEXT,
            LINE_ICD9_DGNS_CD_1 TEXT,
            LINE_ICD9_DGNS_CD_2 TEXT,
            LINE_ICD9_DGNS_CD_3 TEXT,
            LINE_ICD9_DGNS_CD_4 TEXT,
            LINE_ICD9_DGNS_CD_5 TEXT,
            LINE_ICD9_DGNS_CD_6 TEXT,
            LINE_ICD9_DGNS_CD_7 TEXT,
            LINE_ICD9_DGNS_CD_8 TEXT,
            LINE_ICD9_DGNS_CD_9 TEXT,
            LINE_ICD9_DGNS_CD_10 TEXT,
            LINE_ICD9_DGNS_CD_11 TEXT,
            LINE_ICD9_DGNS_CD_12 TEXT,
            LINE_ICD9_DGNS_CD_13 TEXT
            );
        """
    cur.execute(ddl_statement)
